### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by musalbas** [rollkit/docs#117]

**Comment by jcstein** [comment]
This would be an issue to add support for other favicon sizes other than [`favicon.ico`](https://github.com/rollkit/docs/blob/main/static/img/favicon.ico), correct?

**Comment by musalbas** [comment]
No, it's just to add a favicon in the first place, as I only see the default favicon in my browser (Firefox):

![image](https://user-images.githubusercontent.com/5038597/220726002-aa644175-7ece-4dd9-8594-427ef73727b9.png)

**Comment by jcstein** [comment]
Can you try to hard refresh your page to see if the current favicon updates?

Regarding sizing, I understand and will modify it and make a PR to resolve this

**Comment by musalbas** [comment]
I can see it now after hard refresh!

**Comment by jcstein** [comment]
Preview of full height on a white background for demonstration purposes:
![android-chrome-192x192](https://user-images.githubusercontent.com/46639943/220728938-9e7e0818-f635-49bb-99c7-8e7b1f2ca1dd.png)

**Comment by musalbas** [comment]
Should be transparent like https://blog.celestia.org/favicon.png as browser tabs have different colour bgs

**Comment by jcstein** [comment]
✅ got it. without background was not the best way to demo sizing 😄:
![android-chrome-192x192](https://user-images.githubusercontent.com/46639943/220729607-f4f10f2e-68d1-4670-aa11-130bd94e6792.png)
