### ISSUE TITLE
Ethermint Rollup Start Command Error

### ISSUE THREAD

**Issue by pynchmeister** [rollkit/docs#174]
The current command: 

```ethermintd start --rollkit.aggregator true --rollkit.da_layer celestia --rollkit.da_config='{"base_url":"http://localhost:26659","timeout":60000000000,"gas_limit":6000000,"fee":6000}' --rollkit.namespace_id $NAMESPACE_ID --rollkit.da_start_height $DA_BLOCK_HEIGHT ```

seems like it should be:

```ethermintd start --rollmint.aggregator true --rollmint.da_layer celestia --rollmint.da_config='{"base_url":"http://localhost:26659","timeout":60000000000,"gas_limit":6000000,"fee":6000}' --rollmint.namespace_id $NAMESPACE_ID --rollmint.da_start_height $DA_BLOCK_HEIGHT ```

**Comment by jcstein** [comment]
good eye! didn't see this but someone fixed something similar in #178 

would you like to make a pr to fix remaining instances?

**Comment by jcstein** [comment]
hm, after looking at this further, the command should have `rollkit` and not `rollmint`
