### ISSUE TITLE
Base url not being applied to all links

### ISSUE THREAD

**Issue by MSevey** [rollkit/docs#209]
### Version of Git SHA

main

### System OS

github runners

### Steps to reproduce it

create a PR and try and navigate the pr preview

### Expected result

the `pr-preview/pr-##` should stay in the url as you navigate the site to ensure that you are seeing the actual preview and not the main deployed site. 

### Actual result

the base url is only applied to the home page.

**Comment by MSevey** [comment]
This: https://vitepress.dev/reference/site-config#base

Seems to imply we just need to define it once, but it doesn't seem to be sticking. 

Maybe it's a bug with vitepress?

Locally when I try clicking around the site, I start getting this
```
http://localhost:5173/testing/testing/testing/reference/testing/tutorials/testing/reference/testing/testing/testing/testing/testing/
```

**Comment by jcstein** [comment]
it looks like it works on #210 preview https://rollkit.dev/pr-preview/pr-210/tutorials/gm-world-frontend

**Comment by jcstein** [comment]
seems to be working in #204 as well now 😄

**Comment by jcstein** [comment]
<img width="424" alt="testing 2023-08-10 at 13 15 14" src="https://github.com/rollkit/docs/assets/46639943/6aaf2525-4d38-4b0c-9416-9f4d2c9f2f04">
