### ISSUE TITLE
Install Rollkit steps not working

### ISSUE THREAD

**Issue by PaulRBerg** [rollkit/docs#223]
## Context

Source: https://rollkit.dev/tutorials/gm-world#install-rollkit

Running `go mod tidy` produces the following error:

```text
go: downloading github.com/rollkit/cosmos-sdk v0.46.13-rollkit-v0.9.0-no-fraud-proof
gm/app imports
	github.com/cosmos/cosmos-sdk/baseapp: reading github.com/rollkit/cosmos-sdk/go.mod at revision v0.46.13-rollkit-v0.9.0-no-fraud-proof: unknown revision v0.46.13-rollkit-v0.9.0-no-fraud-proof
```

You can see the full logs [here](https://app.warp.dev/block/3e1i5Gqv8kSHbAlPscoXsl).
```[tasklist]
### Tasks
```

## Environment

- macOS@13.4.1
- go@v1.20.7

**Comment by PaulRBerg** [comment]
Nevermind, I ran each command individually rather than copy-pasting all four commands.

After running them together, the download worked.

**Comment by PaulRBerg** [comment]
Seems

**Comment by PaulRBerg** [comment]
After running `go clean -modcache` and then using the updated command provided by @jcstein in this PR https://github.com/rollkit/docs/pull/216, I was still not able to get rid of the protobuf error. See the full logs [here](https://app.warp.dev/block/fQ418MvefHe3diU8fikGN9).

**Comment by jcstein** [comment]
thanks for submitting these issues @PaulRBerg - taking a look into these and hope to have a resolution for you soon
