### ISSUE TITLE
401 Unauthorized unmarshaling response

### ISSUE THREAD

**Issue by PaulRBerg** [rollkit/docs#231]
## Context

Source: https://rollkit.dev/tutorials/gm-world#start-your-rollup

Running the `init-local.sh` script works now, but I am getting the following errors:

> RPC client error: sendRequest failed: http status 401 Unauthorized unmarshaling response: EOF

Full logs [here](https://app.warp.dev/block/leTR1NxnMtH2mPFILUI8js).

## Environment

- macOS@13.4.1
- go@v1.20.7

**Comment by jcstein** [comment]
what version of ignite-cli are you on?

did you rebuild the gmd binary?

attempting to reproduce myself now

**Comment by jcstein** [comment]
pulling these from your logs for vis

```bash
3:34PM INF indexed block height=30 module=txindex
2143:34PM INF Creating and publishing block height=31 module=BlockManager
2153:34PM INF minted coins from module account amount=411947419464369516stake from=mint module=x/bank
2163:34PM ERR DA layer submission failed error="RPC client error: sendRequest failed: http status 401 Unauthorized unmarshaling response: EOF" attempt=1 module=BlockManager
2173:34PM ERR DA layer submission failed error="RPC client error: sendRequest failed: http status 401 Unauthorized unmarshaling response: EOF" attempt=2 module=BlockManager
...
```

**Comment by jcstein** [comment]
also, while trying to reproduce this, I am noticing that in the rollkit logs there is no longer a line of the format:
```
2:11PM INF successfully submitted Rollkit block to DA layer daHeight=42606 module=BlockManager rollkitHeight=4
```

just these:
```
6:50PM INF indexed block height=200 module=txindex
6:50PM INF Creating and publishing block height=201 module=BlockManager
6:50PM INF minted coins from module account amount=411959957677506844stake from=mint module=x/bank
6:50PM INF commit synced commit=436F6D6D697449447B5B3939203438203232322031393120323036203131382032333220313137203437203630203334203234372031383920313938203230372032323520313520333320343120323920323237203130322038342031393920323120313933203133372031383120343920313637203137362032395D3A43397D module=server
```

**Comment by PaulRBerg** [comment]
> what version of ignite-cli are you on?

the latest, v0.27.1

> did you rebuild the gmd binary?

yes

**Comment by PaulRBerg** [comment]
#234 didn't fix this

**Comment by jcstein** [comment]
I wasn't able to reproduce this yesterday, starting another instance to see if i can hit this issue now

**Comment by jcstein** [comment]
I was able to reproduce [here](https://app.warp.dev/block/wjzbAuxKVCJXwCd0VDgaJn)

**Comment by jcstein** [comment]
and was not able to reproduce this on arabica, using light node running v0.11.0-rc8

[logs here](https://app.warp.dev/block/hfymWaGQYlp34Eyp10mZbq)

**Comment by PaulRBerg** [comment]
@jcstein reproduced with v0.11.0-rc8

- [Celestia light node](https://app.warp.dev/block/nQQ8Ocz0R9PpPgqTpwTQct)
- [Rollkit `gm`](https://app.warp.dev/block/HuiKzxp6HEbTdgz6qaawC9)

**Comment by jcstein** [comment]
thank you @PaulRBerg - you haven't reproduced on a live testnet like Arabica though, right? I'm thinking it may be something specific to local-devnet

**Comment by jcstein** [comment]
cc @rollkit/celestia for visibility

**Comment by tuxcanfly** [comment]
Would be good to confirm this is not due to auth token mismatch:

```docker exec $(docker ps -q)  celestia bridge --node.store /bridge  auth admin```

should give you the local celestia devnet bridge node auth token. Assuming there's only one container, otherwise you can pass the container name.

**Comment by tuxcanfly** [comment]
To be clear I saw `401 Unauthorized unmarshaling response: EOF` when the auth token provided in `init-local.sh` *does not* match the token provided by the node. So wasn't able to repro with the right token provided.

**Comment by PaulRBerg** [comment]
Oh shoot, yes, I was using an auth token from another light node I spun up before.

Can confirm that now, after putting the right token in `init-local.sh`, running the `gm` works without any 401 Unauthorized errors!

Thanks for your help, guys.

**Comment by jcstein** [comment]
glad to hear it! i'm about to get around to editing the tutorial to use this method instead of copying from logs :)

thank you @PaulRBerg and @tuxcanfly !

**Comment by jcstein** [comment]
linking this PR with some fixes in case you are trying out FN + SN setup or anything!

https://github.com/rollkit/docs/pull/241
