### ISSUE TITLE
invalid Bech32 prefix; expected celestia, got gm

### ISSUE THREAD

**Issue by PaulRBerg** [rollkit/docs#233]
## Context

Source: https://rollkit.dev/tutorials/gm-world#transactions

Running this command:

```shell
gmd tx bank send $KEY1 $KEY2 42069stake --keyring-backend test
```

Produces this error:

> Error: rpc error: code = InvalidArgument desc = invalid Bech32 prefix; expected celestia, got gm: invalid request

This is immediately after running the `init-local.sh` script. Full logs [here](https://app.warp.dev/block/gsHFMiWoQTmZP31QnoGgwL).

Could this be related to https://github.com/rollkit/docs/issues/231?

## Environment

- macOS@13.4.1
- go@v1.20.7

**Comment by jcstein** [comment]
confirming that i can reproduce this on latest of gm world tutorial

i think that for this, we may need to manually set the RPC URL for gmd as it is finding the default as the celestia-local-devnet at 26657

looking into this

**Comment by PaulRBerg** [comment]
Can confirm that #234 fixes this
