### ISSUE TITLE
[Feature Request]: Redirect old links

### ISSUE THREAD

**Issue by nashqueue** [rollkit/docs#254]
### Implementation ideas

See if there is a way to redirect old links to the current site structure. 
For example, https://rollkit.dev/blog/sovereign-rollups-on-bitcoin/ Link from our Tweet should be redirected to https://rollkit.dev/blog/sovereign-rollups-on-bitcoin-with-rollkit

**Comment by jcstein** [comment]
it appears there is no default way to do this in vitepress, so doing it similarly to how this was done for redirecting to celestia-app specs may be the answer for now: https://github.com/celestiaorg/docs/blob/fa0b4d804e5b3937ec4bbd827debe23deebcaf9d/docs/learn/specifications/reserved-namespaces.md?plain=1

alternatively, we can just rename the link to "/sovereign-rollups-on-bitcoin" to preserve old links

**Comment by nashqueue** [comment]
Yeah,thats a great idea.  Renaming it might be the low-hanging fruit here.

**Comment by jcstein** [comment]
i don't believe there are any others that need updating, but if that changes, we can reopen this issue

just to confirm, you don't want to add back in "/docs/" to the URL paths? IMO it just is clunky for no real gains

for example, after is how it would look with docs in path:
- before: https://rollkit.dev/tutorials/gm-world
- after https://rollkit.dev/docs/tutorials/gm-world
