### ISSUE TITLE
Create a seperate section how to test and maintain with  local celestia devnet 

### ISSUE THREAD

**Issue by nashqueue** [rollkit/docs#267]
Is there some other place where we could add this information. Is it relevant for the developer? Maybe have a separate localcelestia-devnet section or adding it to the Read me ? Thinking out loud , wdyt

_Originally posted by @nashqueue in https://github.com/rollkit/docs/pull/266#discussion_r1394314160_

**Comment by jcstein** [comment]
relevant for issues @mycodecrafting is facing

**Comment by jcstein** [comment]
partially closed in https://github.com/rollkit/docs/pull/290
