### ISSUE TITLE
feat: document setting gas with celestia-da and local-celestia-devnet

### ISSUE THREAD

**Issue by jcstein** [rollkit/docs#300]
summary from @tuxcanfly:

either you can configure a global default for *all* tx going through celestia-da with it's flag `--da.grpc.gasprice`

examples:

- use the current default for testnet: `-da.grpc.gasprice=0.1` will calculate fee using `0.1 utia/gas` fee rate
- bump up the fee if blocks are full: `-da.grpc.gasprice=0.5` will calculate fee using `0.5 utia/gas` fee rate
- lets node use app defaults: `-da.grpc.gasprice=-1` this will use node to calculate fee rate from app, use that rate

*or* you can configure it from rollkit with it's flag `--rollkit.da_gas_price` and bump it up and down without changing celestia-da

- both accept a `float64`  which is the gas price in utia per gas unit

**Comment by Manav-Aggarwal** [comment]
documented already.
