### ISSUE TITLE
feat: point to the latest releases to cosmos-sdk@v0.50.1-rollkit-v0.11.19-no-fraud-proofs against v0.12.8 celestia-da

### ISSUE THREAD

**Issue by jcstein** [rollkit/docs#301]
Requires updating and testing all tutorials

- [ ] gm world local devnet
- [ ] gm world mocha
- [ ] gm world mainnet
- [ ] recipes book to arabica
- [ ] wordle to arabica
- [ ] cosmwasm (still needs to be bumped to a newer version in #299 )
- [x] polaris local
- [x] polaris mocha

**Comment by jcstein** [comment]
can't build on recipes rollup
https://app.warp.dev/block/g5m6wRACnGtKX3bbbsI8s6

**Comment by Manav-Aggarwal** [comment]
Closing since we don't maintain a cosmos-sdk fork anymore, nor local-celestia-devnet
