### ISSUE TITLE
[Feature Request]: Consider removing the script in the front-end tutorial

### ISSUE THREAD

**Issue by S1nus** [rollkit/docs#376]
### Implementation ideas

the curl + bash script to install the front-end tutorial is oversimplification.

Although simplicity is the most-important design goal, it is very important not to _obfuscate complexity_, especially when the script is already 4 simple commands: `git`, `cd`, `yarn install`, and `yarn run dev`. These tools are familiar and beloved for most devs, IMO we shouldn't hide them behind a script.

**Comment by jcstein** [comment]
resolved in #380
