### ISSUE TITLE
update rollkit using ignite app

### ISSUE THREAD

**Issue by gupadhyaya** [rollkit/docs#378]
https://github.com/ignite/apps/pull/88

```
ignite s chain gm --address-prefix gm
cd gm
ignite app install -g github.com/ignite/apps/rollkit@rollkit/v0.1.0
ignite rollkit add
ignite chain build
```

**Comment by toschdev** [comment]
ignite s chain gm --address-prefix gm
cd gm
ignite app install -g github.com/ignite/apps/rollkit@rollkit/v0.2.1
ignite rollkit add
ignite chain build

**Comment by Manav-Aggarwal** [comment]
Already updated
