### ISSUE TITLE
add DA and P2P components to `rollkit-stack.md`

### ISSUE THREAD

**Issue by Manav-Aggarwal** [rollkit/docs#59]
Add docs for enabling gossiping:

Currently, there is no documentation about how to configure gossiping where we need to have to pass some flags along with seed node addresses in order to have different nodes be able to discover each other in the p2p layer

**Comment by jcstein** [comment]
can you provide more guidance so I can work this in to docs?

**Comment by Manav-Aggarwal** [comment]
Waiting on guidance as well from @tzdybal
