### ISSUE TITLE
Setup DNS for Rollkit site

### ISSUE THREAD

**Issue by jcstein** [rollkit/docs#9]
talk to Mustafa

**Comment by musalbas** [comment]
done, you need to add a cname file now
https://rollkit.dev

**Comment by jcstein** [comment]
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by jcstein** [comment]
thanks @musalbas. done. https://github.com/rollkit/docs/blob/gh-pages/CNAME
